---
hero_image: images/weather-logger.png
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
title: Weerlogboek
description: Leg gegevens van de sensoren vast en geef ze weer in een lijngrafiek.
original_url: https://codeclubprojects.org/en-GB/sense-hat/weather-logger
interests: weather
technologies: sense-hat
site_areas: projects
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps:
- title: Inleiding
  completion: engaged
- title: Vastleggen van temperatuur
- title: Een temperatuurgrafiek maken
- title: 'Uitdaging: simuleer verschillende weersomstandigheden'
  completion: internal
- title: 'Uitdaging: registreer de vochtigheid of druk'
