---
hero_image: images/weather-logger.png
theme: blå
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 2, design-0, programmering-2, phys-comp-0, tillverkning-0, community-0
title: Weather Logger
description: Log data from the sensors and then display it as a line graph.
original_url: https://codeclubprojects.org/en-GB/sense-hat/weather-logger
interests: väder
technologies: sense-hat
site_areas: projekt
hardware: sense-hat
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 'Introduction'
  - 
    title: Logging the temperature
  - 
    title: Creating a temperature graph
  - 
    title: 'Challenge: Simulate different weather conditions'
  - 
    title: 'Challenge: Record humidity or pressure'
